VOXCONVERT: extended voxconvert shell script test
but vox<=>qb is still disabled

diff --git a/src/tools/voxconvert/tests/tests.sh.in b/src/tools/voxconvert/tests/tests.sh.in
--- a/src/tools/voxconvert/tests/tests.sh.in
+++ b/src/tools/voxconvert/tests/tests.sh.in
@@ -5,19 +5,45 @@ set -e
 BINARY=$1
 FILE=voxedit/chr_knight.qb
 
+function convert() {
+  src_format=$1
+  target_format=$2
+
+  echo "prepare a ${src_format} file that is written by the current version (@DATA_DIR@/$FILE)"
+
+  src_file=@CMAKE_BINARY_DIR@/${FILE%.*}.${src_format}
+  target_file=@CMAKE_BINARY_DIR@/${FILE%.*}.${target_format}
+  final_file=@CMAKE_BINARY_DIR@/${FILE%.*}-${target_format}.${src_format}
+
+  $BINARY -f --input @DATA_DIR@/$FILE --output ${src_file}
+  echo
+  echo "now convert to ${target_format} and back to ${src_format} to verify that everything works"
+  $BINARY -f --input ${src_file} --output ${target_file}
+  $BINARY -f --input ${target_file} --output ${final_file}
+  echo
+  set +e
+  diff ${src_file} ${final_file}
+  if [ $? -ne 0 ]; then
+    echo "Error: files shouldn't be different"
+    echo "src file ($BINARY --input ${src_file} --dump)"
+    $BINARY --input ${src_file} --dump
+    echo "final file ($BINARY --input ${final_file} --dump)"
+    $BINARY --input ${final_file} --dump
+    exit 1
+  fi
+  set -e
+}
+
 if [ -z "$BINARY" ]; then
   BINARY=@CMAKE_BINARY_DIR@/@PROJECT_NAME@/@CMAKE_PROJECT_NAME@-@PROJECT_NAME@
 fi
 
-echo "prepare a file that is written by the current version (@DATA_DIR@/$FILE)"
-$BINARY -f --input @DATA_DIR@/$FILE --output @CMAKE_BINARY_DIR@/${FILE%.*}.vox
-echo
-echo "now convert to qubicle and back to vox to verify that everything works"
-$BINARY -f --input @CMAKE_BINARY_DIR@/${FILE%.*}.vox --output @CMAKE_BINARY_DIR@/${FILE%.*}.qb
-$BINARY -f --input @CMAKE_BINARY_DIR@/${FILE%.*}.qb --output @CMAKE_BINARY_DIR@/${FILE%.*}-qb.vox
-echo
-# TODO: activate me
-#diff @CMAKE_BINARY_DIR@/${FILE%.*}.vox @CMAKE_BINARY_DIR@/${FILE%.*}-qb.vox
+convert vxm qb
+convert qbcl qb
+convert qbt qb
+convert cub qb
+# TODO: this is still broken and needs investigation
+#convert vox qb
 
 echo "export layers of @DATA_DIR@/$FILE"
 cp @DATA_DIR@/$FILE @CMAKE_BINARY_DIR@
